export const CHANGE_TEXT = 'CHANGE_TEXT';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const UNSELECTED_CATEGORY = 'UNSELECTED_CATEGORY';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';
