// Categories
export const CHANGE_TEXT_CATEGORY = 'CHANGE_TEXT_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const UNSELECTED_CATEGORY = 'UNSELECTED_CATEGORY';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';
// Locations
export const CHANGE_TEXT_LOCATION = 'CHANGE_TEXT_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const SELECTED_LOCATION = 'SELECTED_LOCATION';
export const UNSELECTED_LOCATION = 'UNSELECTED_LOCATION';
export const RENAME_LOCATION = 'RENAME_LOCATION';
export const SORT_LOCATIONS = 'SORT_LOCATIONS';
